# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ "api.volt.link" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: run deploy commands on uberspace
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd ~/api.volt.link/ && git pull && yarn && supervisorctl restart api_volt_link;
          host: maury.uberspace.de
          username: volteu
          password: ${{ secrets.UBERSPACE_PASSWORD_VOLTEU }}
